//
//  RegisterModels.swift
//  SwiftArquiteturas
//
//  Created by Enrico Sousa Gollner on 15/06/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Register
{
    // MARK: Use cases
    
    enum Something
    {
        struct Request
        {
            public var userModel: UserModel
        }
        struct Response
        {
            public var userModel: UserModel
        }
        struct ViewModel
        {
            public var userModel: UserModel
        }
        struct ViewError: Error {
            public var error: Error
        }
    }
}
