//
//  RegisterRouter.swift
//  SwiftArquiteturas
//
//  Created by Enrico Sousa Gollner on 15/06/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol RegisterRoutingLogic
{
    func routeToHome()
    func routeToLogin()
}

protocol RegisterDataPassing
{
    var dataStore: RegisterDataStore? { get }
}

class RegisterRouter: NSObject, RegisterRoutingLogic, RegisterDataPassing
{
    
    weak var viewController: RegisterViewController?
    var dataStore: RegisterDataStore?
    
    // MARK: Routing
    
    func routeToHome() {
        let destinationVC = HomeViewController()
        navigateToHome(source: viewController!, destination: destinationVC)
    }
    
    func routeToLogin() {
        self.navigateToLogin()
    }
    
    // MARK: Navigation
    
    func navigateToHome(source: RegisterViewController, destination: UIViewController){
        destination.modalPresentationStyle = .fullScreen
        source.navigationController?.pushViewController(destination, animated: true)
    }
    
    func navigateToLogin() {
        self.viewController?.navigationController?.popToRootViewController(animated: true)
    }
}
