//
//  LoginRouter.swift
//  SwiftArquiteturas
//
//  Created by Enrico Sousa Gollner on 15/06/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic
{
    // Definindo as rotas:
    func routeToHome()
    func routeToRegister()
}

protocol LoginDataPassing
{
    var dataStore: LoginDataStore? { get }
}

class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing
{
    weak var viewController: LoginViewController?
    var dataStore: LoginDataStore?
    
    // MARK: Routing
    
    func routeToHome()
    {
        let destinationVC = HomeViewController()
        navigateToPush(source: viewController!, destination: destinationVC)
        
    }
    
    func routeToRegister()
    {
        let destinationVC = RegisterViewController()
        navigateToPush(source: viewController!, destination: destinationVC)
    }
    
    // MARK: Navigation
    func navigateToPush(source: LoginViewController, destination: UIViewController)
    {
        destination.modalPresentationStyle = .fullScreen
        source.navigationController?.pushViewController(destination, animated: true)
    }
    
    // MARK: Passing data
    
    func passDataToModal(source: LoginDataStore, destination: UIViewController)
    {
//        destination.modalPresentationStyle = .fullScreen
//        source.showDetailViewController(destination, sender: source)
    }
}
